Applied astyle. Added astyle formatting check to CI workflow. Updated Readme.

diff --git a/.github/workflows/ci_container_matrix.yaml b/.github/workflows/ci_container_matrix.yaml
--- a/.github/workflows/ci_container_matrix.yaml
+++ b/.github/workflows/ci_container_matrix.yaml
@@ -15,6 +15,33 @@ jobs:
     steps:
       - uses: actions/checkout@v6
 
+      - name: Install astyle
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y astyle
+
+      - name: Check astyle version
+        run: astyle --version
+
+      - name: Run astyle
+        run: astyle --options=astyle-options.ini --mode=c --recursive "./*.c, *.h"
+
+      - name: Get git diff
+        id: diff
+        run: |
+          if git diff --exit-code; then
+            echo "No changes to commit."
+            echo "changes=false" >> $GITHUB_OUTPUT
+          else
+            echo "changes=true" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Assert git diff
+        if: steps.diff.outputs.changes == 'true'
+        run: |
+          echo "::error::There are changes done by astyle."
+          exit 1
+
       - name: Check Podman version
         run: podman --version
 
